version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5
  maven: circleci/maven@1.4.1

executors:
  java:
    docker:
      - image: cimg/openjdk:20.0.1
    resource_class: small


workflows:
  build-test:
    jobs:
      - maven/test:
          executor: java
          post-steps:
            - codecov/upload