version: 2.1
orbs:
  maven: circleci/maven@1.3

executors:
  java:
    docker:
      - image: cimg/openjdk:20.0.1


workflows:
  build-test:
    jobs:
      - maven/test:
          executor: java
          test_results_path: target/surefire-reports